config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views

  root 'welcome#index'
  get '/about' => 'welcome#about' 

  resources :beers

end

app/models/beer.rb
class Beer < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.all
  end

  def new
    @beers = Beer.new
  end

  def create
    @beer = Beer.new
    @beer.name      = params[:beer][:name]
    @beer.beer_type = params[:beer][:beer_type]
    @beer.abv       = params[:beer][:abv]
    @beer.ibu       = params[:beer][:ibu]
    @beer.image     = params[:beer][:image]
    @beer.save!
    redirect_to beers_path
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy
    redirect_to beers_path
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.name      = params[:beer][:name]
    @beer.beer_type = params[:beer][:beer_type]
    @beer.abv       = params[:beer][:abv]
    @beer.ibu       = params[:beer][:ibu]
    @beer.image     = params[:beer][:image]
    @beer.save!
    redirect_to beers_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/edit.html.erb
<h2>Edit yo beer!</h2>
<%= form_for @beer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :beer_type %>
  <%= f.text_field :beer_type %>
  <%= f.label :abv, "ABV%" %>
  <%= f.text_field :abv %>
  <%= f.label :ibu, "IBU" %>
  <%= f.text_field :ibu %>
  <%= f.label :image, "ImageURL" %>
  <%= f.text_field :image %>
  <%= f.submit "Update Beer" %>

<% end %>

app/views/beers/index.html.erb
<h1> Boulder Beers </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>ABV%</th>
      <th>IBUs</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @beers.each do |beer| %>
      <td><%= beer.name %></td>
      <td><%= beer.beer_type %></td>
      <td><%= beer.abv %></td>
      <td><%= beer.ibu %></td>
      <!-- <td><%= beer.image %></td> -->
      <td><%= link_to "View Beer", beer, class: "btn btn-success" %></td>
      <td><%= link_to "Edit Beer", edit_beer_path(beer), class: "btn btn-info" %></td>
      <td><%= link_to beer, method: :delete, data: {confirm: 'Are you sure?'} do %>
      <span class="btn btn-danger">Eliminate Beer</span>
      <% end %></td>
    </tr>
    <% end %>

  </tbody>
</table>

<%= link_to "Add New Beer", new_beer_path, class: "btn btn-warning" %>

app/views/beers/new.html.erb
<h1>Add a new beer!</h1>
<%= form_for @beers do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :beer_type %>
  <%= f.text_field :beer_type %>
  <%= f.label :abv, "ABV%" %>
  <%= f.text_field :abv %>
  <%= f.label :ibu, "IBU" %>
  <%= f.text_field :ibu %>
  <%= f.label :image, "ImageURL" %>
  <%= f.text_field :image %>
  <%= f.submit "Add Beer" %>

<% end %>

app/views/beers/show.html.erb
<h3><%= @beer.name %> </h3>
<p>Type: <%= @beer.beer_type %></p>
<p>ABV %: <%= @beer.abv %></p>
<p>IBU's: <%= @beer.ibu %></p>
<p>Photo: <%= image_tag @beer.image %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Boulder Brews</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/about">About</a></li>
        <li><%= link_to "Beer List", beers_path %> </li>
        <!-- <li><a href="#">Locations</a></li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
        <li><%= link_to "Purveyor Log-In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<!-- <%= role="navigation" %> -->
<% if flash[:success] %>
  <%= flash[:success] %>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h2>About our Saturday</h2>
<p> Luke and Jessica came together over a shared love of programming.
From opposing sides of the world, GSchool and Turing, they came together to make an app about beers and stuff.</p> 

app/views/welcome/index.html.erb
<h1>Hello Railsbridge</h1>
<p> We made a beer app!</p>
<%= image_tag "luke_jess.jpg", width: 500 %> 